name: 'Close stale issues'

on:
  schedule:
    - cron: '0 */12 * * *'
  issue_comment:
    types: [created]

permissions: {}

jobs:
  stale:
    permissions:
      issues: write # to comment on issues
      pull-requests: write # to comment on pull requests

    runs-on: ubuntu-latest
    steps:
      - uses: DeMoorJasper/stale@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-label: Stale
          stale-message: >
            This issue has been automatically marked as stale because
            it has not had recent activity. It will be closed in 14 days if no
            further activity occurs.
          days-before-stale: 180
          days-before-close: 14
          exempt-labels: 'pinned, Stale Ignore, security, Confirmed Bug, Feature, parcel 2'
          dry-run: 'false'
